server:
  port: 7003

eureka:   #eureka 服务注册中心 （相当于物业）
  instance:
    hostname: eureka7003.com #rureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false  #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索职务
    service-url: #相当于业主向物业交物业费的银行账户
      #单机版defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与Eureka  server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/